# Generated by Django 4.2 on 2023-06-14 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_in_watchlist',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='watchlist',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AddField(
            model_name='listing',
            name='user_watchlist',
            field=models.ManyToManyField(blank=True, related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
