# Generated by Django 4.2 on 2023-05-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['bid']},
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.ManyToManyField(blank=True, null=True, related_name='Bids', to='auctions.bid'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('listings', models.ManyToManyField(blank=True, null=True, related_name='Listings', to='auctions.listing')),
            ],
        ),
    ]
