# Generated by Django 4.2 on 2023-05-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_options_alter_listing_price_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='Listings', to='auctions.listing'),
        ),
    ]
