# Generated by Django 4.2 on 2023-05-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_category_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.ManyToManyField(blank=True, related_name='Bids', to='auctions.bid'),
        ),
    ]
