# Generated by Django 4.2 on 2023-05-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_in_watchlist',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
