# Generated by Django 4.2 on 2023-05-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_comment_alter_listing_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comments', to='auctions.comment'),
        ),
    ]
